# Generated by Django 4.2.6 on 2023-10-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_purchase_return_time_return_return_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_time',
            new_name='bought_at',
        ),
    ]
